### ISSUE TITLE
mb_eregi_replace() expects parameter 3 to be string, null given

### ISSUE THREAD

**Issue by repat** [paquettg/php-html-parser#190] opened 2019-08-30 02:46 UTC
![image](https://user-images.githubusercontent.com/516807/63989570-99c0d480-ca95-11e9-8bce-348c7933e25f.png)

![image](https://user-images.githubusercontent.com/516807/63989624-caa10980-ca95-11e9-8ff6-73d7e7d815c2.png)

Pretty odd, I can't find that in your code, since it's only in `Dom.php`@ `clean()` and `$str` has to be a string 🤔 any ideas?

* Version 2.1
* PHP 7.3.8

**Comment by paquettg** [comment] 2019-09-02 01:13
Hey @repat ,

mb_eregi_* methods can return false/null if it encounters an error of some kind. I am not able to reproduce this as of yet.

Can you please provide me with the full stack trace and some example html that is causing this to happen for you?

Thank you.

**Comment by luyi61** [comment] 2019-09-02 03:45
Same problem. It happened when I loaded a url and the site meta charset is GBK. 

Site Url: "https://zhidao.baidu.com/question/521824455220270725.html"

**Comment by maksa988** [comment] 2019-09-06 07:51
Same problem, site URL: https://forinsurer.com/ratings/banks/17/3/14

**Comment by Aigleblanc** [comment] 2019-09-13 21:07
I have same problem,

**Comment by MindFlare56** [comment] 2019-09-15 12:17
It looks like this happen when the HTML is gzipped.
It gave me the same problem with amazon.com and that's what I found out searching for a solution.

Content-Encoding: gzip

**Comment by Aigleblanc** [comment] 2019-09-15 13:05
I have the problem on the same site personally but between different URLs that display the same data structure yet

**Comment by paquettg** [comment] 2019-09-28 01:39
Added code recommended by @Aigleblanc. Fix will be released as part of 2.1.1

**Closed by paquettg** 2019-09-28 01:39 UTC
Labels: bug

**Comment by ozonar** [comment] 2020-03-16 12:15
I see this error (after fix) if opened file in Windows-1251 encoding.

**Comment by notb0t** [comment] 2020-03-27 09:06
same problem after fix

**Comment by haisamhameed** [comment] 2020-05-15 20:44
I had the same issue none of the above worked for me , 
$content = iconv('windows-1251', 'utf-8', $content);
$dom->load($content);
this one worked for me

**Comment by mostafaznv** [comment] 2020-11-09 16:32
I had same issue
I changed line 531 in Dom.php to this:
```
$str = mb_eregi_replace("'\s+>", "'>", mb_convert_encoding($str, 'utf-8'));
```

and everything works nice.

**note**: I didn't change package source code. but I created a `Guzzle Client Interface` ([documentation](https://github.com/paquettg/php-html-parser/#loading-urls)) and I changed it there.

**Comment by baghbanM** [comment] 2025-01-15 05:25
> I had same issue I changed line 531 in Dom.php to this:
> 
> ```
> $str = mb_eregi_replace("'\s+>", "'>", mb_convert_encoding($str, 'utf-8'));
> ```
> 
> and everything works nice.
> 
> **note**: I didn't change package source code. but I created a `Guzzle Client Interface` ([documentation](https://github.com/paquettg/php-html-parser/#loading-urls)) and I changed it there.

This code works for me. thx

**Comment by baghbanM** [comment] 2025-01-15 07:12
> > I had same issue I changed line 531 in Dom.php to this:
> > ```
> > $str = mb_eregi_replace("'\s+>", "'>", mb_convert_encoding($str, 'utf-8'));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and everything works nice.
> > **note**: I didn't change package source code. but I created a `Guzzle Client Interface` ([documentation](https://github.com/paquettg/php-html-parser/#loading-urls)) and I changed it there.
> 
> This code works for me. thx

Can anyone change the source code?

**Comment by repat** [comment] 2025-01-15 10:16
@baghbanM:  @paquettg can :) maybe it wasn't fixed in 2019 after all?

**Comment by baghbanM** [comment] 2025-01-15 10:38
@repat @paquettg 

hi 

No. I am using the new version but I am getting this error.

mb_eregi_replace(): Argument #3 ($string) must be of type string, null given

**Comment by MindFlare56** [comment] 2025-01-15 12:31
The issue was definitely not fixed in 2019 even though I gave a simple and detailed solution lmao

**Comment by mostafaznv** [comment] 2025-01-15 12:34
It appears that this repository is no longer being maintained.

**Comment by baghbanM** [comment] 2025-01-15 12:51
Is there an alternative version?

**Comment by mostafaznv** [comment] 2025-01-15 12:56
I haven’t tried anything else since then. To be honest, I don’t even remember which project I used this package for.
Take a look at `packagist`; there should be some alternatives there.

That said, I recommend fixing the bug using the solution I mentioned a couple of messages ago.

**Comment by baghbanM** [comment] 2025-01-15 12:57
Can I replace the code in the package?

**Comment by mostafaznv** [comment] 2025-01-15 13:06
> Can I replace the code in the package?

It’s not a good practice. Instead, implement a new `Dom` class (extending `PHPHtmlParser\Dom`) and modify it to suit your needs

**Comment by baghbanM** [comment] 2025-01-15 13:18
Dom = new Dom;
Dom->loadFromUrl($link);

how to use ($str = mb_eregi_replace("'\s+>", "'>", mb_convert_encoding($str, 'utf-8'));)  ?????????????????

thx

**Comment by mostafaznv** [comment] 2025-01-15 13:37
> Dom = new Dom; Dom->loadFromUrl($link);
> 
> how to use ($str = mb_eregi_replace("'\s+>", "'>", mb_convert_encoding($str, 'utf-8'));) ?????????????????
> 
> thx


Please share a gist demonstrating the issue. I’ll review it tonight and get back to you with a possible fix or solution.

**Comment by baghbanM** [comment] 2025-01-16 04:27
@mostafaznv How can I send a private message?

**Comment by mostafaznv** [comment] 2025-01-16 18:08
> [@mostafaznv](https://github.com/mostafaznv) How can I send a private message?

Being part of the open-source community, it would be better if we solved the problem here. The possible fix might help others.
