### ISSUE TITLE
[Bug] Elements not found

### ISSUE THREAD

**Issue by HarpyWar** [paquettg/php-html-parser#104] opened 2017-01-05 14:49 UTC
HTML document example http://pastebin.com/mp2vBeV7

`$dom->find('a');` return wrong count of elements. Or `$dom->find('.ctitem');`, or `$dom->find('.link_item_block');`.
I think it's because of many tags inside `<a>` element. It seems to work if clean them all.

But anyway it's a bug. Regular PHP `DomDocument` with `DomXPath` works fine with this HTML example.

**Comment by HarpyWar** [comment] 2017-01-05 21:24
Another bug.
```
<div class='foo'></span>sometext</div>
```
`innerHtml` property of the <div> node above is be empty, instead of `sometext`.

**Comment by godbout** [comment] 2017-01-27 06:31
Same here. Wrong count and number of objects returned, possibly because the tags contain too much inner tags? (trying to catch trs).

**Comment by HarpyWar** [comment] 2017-01-28 09:20
I guess to except these bugs (and possible others) it will be better if a parsing library will be based on `DomDocument` but provide easier interface like php-html-parser.
For now I decided to use `DomDocument`, because reliability prevails over convenience in this case.

**Comment by godbout** [comment] 2017-01-28 17:17
I'm finding the issue is because of misplaced closing span tags. The html coming from the page is not correctly formatted.

**Comment by wintercoder** [comment] 2017-02-15 08:00
Same problem.
`<td class="whitetext"><a class="blue" href="http://demo">sometext</a>author</td>`

I can't get `sometext` or even `sometext</a>author`

**Closed as completed** 2019-02-06 00:26 UTC
Labels: bug
